version: '1'

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dharminder
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - amongus

  api:
    container_name: ipt-cebpeb
    build: 
      context: ./
      dockerfile: Dockerfile
      network: host
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_started
    environment:
      - ConnString=User ID=postgres;Password=postgres;Server=postgres;Port=5432;Database=dharminder;Pooling=true;
    networks:
      - amongus

networks:
  amongus:
    driver: bridge
    
    