import { Button, Flex, useColorMode, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FC, useEffect, useMemo, useState } from "react";

const Home: NextPage = () => {
  const [counter, setCounter] = useState(0);
  const { toggleColorMode } = useColorMode();

  useEffect(() => {
    setTimeout(() => {
      setCounter(counter + 1);
    }, 1000);
  }, [counter]);

  return (
    <Flex height="100vh" justifyContent="center" alignItems="center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack>
        <Button colorScheme="blue" onClick={() => setCounter(counter + 1)}>
          {counter}
        </Button>
        <Button onClick={toggleColorMode}>change theme</Button>
        <Link href="/amongus">
          <button>amongus</button>
        </Link>
      </VStack>
    </Flex>
  );
};

export default Home;
