// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ipt_project_cepbep.Data;

#nullable disable

namespace iptprojectcepbep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ipt_project_cepbep.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("771af60b-2adc-470e-afd0-07d22f6b71ed"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nathen44@hotmail.com",
                            Password = "8qWEtNWDfT",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(6688),
                            Username = "Willis_West18"
                        },
                        new
                        {
                            UserId = new Guid("83951d9d-9f95-4050-90f8-7e2e35f1c7c5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brennan_Stoltenberg37@hotmail.com",
                            Password = "45sgA3iKli",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(7142),
                            Username = "Aurelia_Ward"
                        },
                        new
                        {
                            UserId = new Guid("411ac347-be5e-4281-9270-2bcb76372f6d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jewel.Koss@hotmail.com",
                            Password = "VxdhIgA5SQ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(7532),
                            Username = "Reid.Rohan66"
                        },
                        new
                        {
                            UserId = new Guid("ddaa7556-03b5-4e7f-b5c2-fa7fb8ff6f7b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marisol.Klein@hotmail.com",
                            Password = "1N1X6mCXqH",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(7790),
                            Username = "Leif_Hansen76"
                        },
                        new
                        {
                            UserId = new Guid("5f555561-6f2d-49f0-b811-43525dbb6c89"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Chanelle21@hotmail.com",
                            Password = "hrL4cFoLwa",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(8185),
                            Username = "Freddy.Hamill"
                        },
                        new
                        {
                            UserId = new Guid("1a2aaac9-18e0-4a95-8bc1-da3c27351eb8"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Willie.Kshlerin@gmail.com",
                            Password = "liR6oR5eAK",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(8441),
                            Username = "Gene_Rosenbaum38"
                        },
                        new
                        {
                            UserId = new Guid("e3e5461a-d8de-4a12-8080-27aaf3728f0f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jamel.Gibson@gmail.com",
                            Password = "U37Ljn4PuX",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(9098),
                            Username = "Eloisa.Torp"
                        },
                        new
                        {
                            UserId = new Guid("f0b0e7e8-0f7c-42f8-98d5-4681b9ba4190"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alivia.Moore@hotmail.com",
                            Password = "ChgLAXmv79",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(9355),
                            Username = "Adaline_Boyle17"
                        },
                        new
                        {
                            UserId = new Guid("0da4c0f8-4b42-45d0-bfbf-c6643118b88f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Conor_Kulas32@yahoo.com",
                            Password = "yWWNM6SvKx",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(9661),
                            Username = "Emile.Gaylord"
                        },
                        new
                        {
                            UserId = new Guid("af6d9826-d7e2-40d0-85e1-9c26c62cc8af"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gayle48@yahoo.com",
                            Password = "CW0WipXJwB",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 631, DateTimeKind.Utc).AddTicks(9904),
                            Username = "German42"
                        },
                        new
                        {
                            UserId = new Guid("e18630de-d710-45db-86c4-fa63c6dee51c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Santa.Aufderhar89@gmail.com",
                            Password = "u369GgCBTb",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(248),
                            Username = "Lonie44"
                        },
                        new
                        {
                            UserId = new Guid("4862ae57-af4e-4a7a-81ae-1bf7358ad5ee"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adolf.Romaguera@yahoo.com",
                            Password = "Le07RaXso_",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(509),
                            Username = "Annalise.Jaskolski11"
                        },
                        new
                        {
                            UserId = new Guid("682a5533-55d5-4eaa-b8cb-7f7b0aea941f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Augustus_Boehm98@hotmail.com",
                            Password = "Op4sVBnNhF",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(875),
                            Username = "Danial_McClure"
                        },
                        new
                        {
                            UserId = new Guid("923eb8bf-ac86-4cc8-9086-4353079804a2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Vivian28@gmail.com",
                            Password = "BycKvAZngM",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(1478),
                            Username = "Vergie.Johnson"
                        },
                        new
                        {
                            UserId = new Guid("7ae5e501-3e93-4403-bcad-83147da52cf0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aurelio5@hotmail.com",
                            Password = "siKf6oEbuO",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(1808),
                            Username = "Theodora73"
                        },
                        new
                        {
                            UserId = new Guid("4266f7a3-bac7-4991-85da-c0471dc6b6bd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Roosevelt71@gmail.com",
                            Password = "OOEI7j7ko3",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(2232),
                            Username = "Lexus.OConner6"
                        },
                        new
                        {
                            UserId = new Guid("531a314b-6c06-4884-9c7f-cecc942070ab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kassandra36@yahoo.com",
                            Password = "F8APGfZ4y9",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(2604),
                            Username = "Willie.Bernier23"
                        },
                        new
                        {
                            UserId = new Guid("9bc45693-d417-4bfd-94ff-aa2fc816cf5b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kayden8@gmail.com",
                            Password = "j9c8Nyy68x",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(2881),
                            Username = "Alysson.Herman24"
                        },
                        new
                        {
                            UserId = new Guid("2749480d-306d-4e17-ad80-8ff54531ab6a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marcelle_Koss@gmail.com",
                            Password = "fo9wMhtfQK",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(3182),
                            Username = "Marc_Wiegand1"
                        },
                        new
                        {
                            UserId = new Guid("2bd1c08a-4fc1-4972-862d-ecfaa6d32170"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kristopher_Tremblay@yahoo.com",
                            Password = "zHeAnyKycR",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(3440),
                            Username = "Jaime_Smitham"
                        },
                        new
                        {
                            UserId = new Guid("b07576a5-38dd-414b-a4ca-c7c7bfd22402"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Luz26@yahoo.com",
                            Password = "FvX5OE5kTE",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(3819),
                            Username = "Pierre_Herman"
                        },
                        new
                        {
                            UserId = new Guid("35e9fbe6-d789-4bdb-ba79-a77638046cd1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Janis56@gmail.com",
                            Password = "GunWbpTQAw",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(4062),
                            Username = "Mable49"
                        },
                        new
                        {
                            UserId = new Guid("70fc1756-0b0b-406b-9198-ca4338fb8390"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nigel.Daugherty@yahoo.com",
                            Password = "0Gd7FrZL0d",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(4468),
                            Username = "Reva.Mueller"
                        },
                        new
                        {
                            UserId = new Guid("7a94f611-07be-4f1c-8c24-8c84371b15d5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nia91@yahoo.com",
                            Password = "xU4SrwhKYX",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(4711),
                            Username = "Florence_Wiza52"
                        },
                        new
                        {
                            UserId = new Guid("fb9a1c91-21e8-4e84-9cf3-17d34d1960d5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mack_Rohan@gmail.com",
                            Password = "UFKEX585Yz",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(4939),
                            Username = "Harrison.Johnston"
                        },
                        new
                        {
                            UserId = new Guid("92a26097-8efc-4465-b669-1f96065ec6ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gaylord_McCullough1@gmail.com",
                            Password = "1mRCanjfF5",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(5312),
                            Username = "Merl_Lockman"
                        },
                        new
                        {
                            UserId = new Guid("360c8bca-70f3-43da-b60a-aa7bf13fe450"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dakota.Kuhlman44@yahoo.com",
                            Password = "W6IQp7SUyp",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(5545),
                            Username = "Roberta_Howe"
                        },
                        new
                        {
                            UserId = new Guid("d4d4e369-2d8f-44da-8848-4657f50a5862"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trisha_Ebert85@hotmail.com",
                            Password = "osyyXZVF74",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(5916),
                            Username = "Abe_Zieme"
                        },
                        new
                        {
                            UserId = new Guid("367a8065-a638-4002-a6fe-a03c52b8917d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Amely_Bartoletti44@yahoo.com",
                            Password = "D2H88Qq35n",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(6168),
                            Username = "Eldred_Wisoky"
                        },
                        new
                        {
                            UserId = new Guid("caa1cc22-4ced-44c3-99cb-eedfc2d4571b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Willa.Kovacek@gmail.com",
                            Password = "N9yus9teB7",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(6476),
                            Username = "Christine_Simonis54"
                        },
                        new
                        {
                            UserId = new Guid("b551b2b4-2043-42f8-8f78-8d31201b167b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Xavier50@yahoo.com",
                            Password = "Lir1f5OsN3",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(6719),
                            Username = "Ervin.Hagenes"
                        },
                        new
                        {
                            UserId = new Guid("454af8c2-830e-4d78-96b0-a7f2fb85280b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wendy_Barrows95@gmail.com",
                            Password = "h_EVUEByNv",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(7087),
                            Username = "Tressie_Harber41"
                        },
                        new
                        {
                            UserId = new Guid("b901bbc8-e6eb-4a2d-9c45-a25b22499fbd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Michaela_Heathcote93@gmail.com",
                            Password = "eF9DqwNSZ0",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(7345),
                            Username = "Maiya88"
                        },
                        new
                        {
                            UserId = new Guid("812a81bc-aaa2-4a3a-bb0d-274dbd5d7318"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Newell56@yahoo.com",
                            Password = "A5U20C673N",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(7711),
                            Username = "Niko.Botsford"
                        },
                        new
                        {
                            UserId = new Guid("cca79718-e6df-42db-8f65-482860dffb6b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Laurine_Roberts83@yahoo.com",
                            Password = "cxRo23REBl",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(7974),
                            Username = "Quincy79"
                        },
                        new
                        {
                            UserId = new Guid("e3d90ba6-249a-49ba-aca2-22f6e7438358"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Geoffrey60@hotmail.com",
                            Password = "o8lgaRaHKE",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(8345),
                            Username = "Vada.Bechtelar"
                        },
                        new
                        {
                            UserId = new Guid("5bf211eb-a8b5-4d61-ae8e-a3d2dfcd06c1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Addie26@hotmail.com",
                            Password = "Pz_5DMgQDB",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(8575),
                            Username = "Blaise_Mertz"
                        },
                        new
                        {
                            UserId = new Guid("14971bef-8d3a-44ac-9cf9-fc7372f25305"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Amira_Ferry84@gmail.com",
                            Password = "HEd6XATHtH",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(8945),
                            Username = "Aisha_Brekke"
                        },
                        new
                        {
                            UserId = new Guid("bd97640f-e0c5-4474-a800-29f0a7b085bc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mitchell_Herzog20@hotmail.com",
                            Password = "RvzX5_akAq",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(9210),
                            Username = "Jovan71"
                        },
                        new
                        {
                            UserId = new Guid("66301e80-000b-48a0-a1b1-147b5d9694cc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Allison39@hotmail.com",
                            Password = "O1Ge_zynPy",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(9615),
                            Username = "Benton_Farrell"
                        },
                        new
                        {
                            UserId = new Guid("c8f3bc78-08b5-4488-8c48-cbeb45e59719"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wilfredo11@gmail.com",
                            Password = "TIgUF4i69l",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 632, DateTimeKind.Utc).AddTicks(9878),
                            Username = "Kaley_Kilback70"
                        },
                        new
                        {
                            UserId = new Guid("c5334d30-e3d9-481e-a76f-7aedf2a77c42"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Meredith39@hotmail.com",
                            Password = "NlfUm4wdqC",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(245),
                            Username = "Carmelo_Monahan18"
                        },
                        new
                        {
                            UserId = new Guid("555d1360-1dd0-438a-807f-30b4a7d32486"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lysanne.Green@yahoo.com",
                            Password = "wbyxKZPEo7",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(493),
                            Username = "Royal.Dibbert8"
                        },
                        new
                        {
                            UserId = new Guid("24503180-98e7-4e3c-8504-c26b55bfc81c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jamaal.Yundt42@yahoo.com",
                            Password = "otOjGwIFrZ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(784),
                            Username = "Irwin_Reinger"
                        },
                        new
                        {
                            UserId = new Guid("70102603-bf4b-4f4e-a131-9c9650cd372f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jayde_Buckridge@hotmail.com",
                            Password = "Tg8xa8zIfW",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(1050),
                            Username = "Christine_Bechtelar57"
                        },
                        new
                        {
                            UserId = new Guid("8421d449-2d4b-4715-842f-a7e66017e72c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ernestine_Dare@gmail.com",
                            Password = "J6FKTXh1ha",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(1344),
                            Username = "Yolanda18"
                        },
                        new
                        {
                            UserId = new Guid("97fe4930-4e5a-48b3-b2f8-2d29e8b2271a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nina.Witting21@hotmail.com",
                            Password = "NJmSQ6wE8k",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(1581),
                            Username = "Arvilla58"
                        },
                        new
                        {
                            UserId = new Guid("e4bc15ca-f24b-4f59-9a24-9d6a5a50ce57"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rachael_Bergnaum65@gmail.com",
                            Password = "f2Voy_nPs6",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(1981),
                            Username = "Agnes.Stroman42"
                        },
                        new
                        {
                            UserId = new Guid("28768a84-0b70-4af9-87c3-2f3aec23d3f9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Orval_Douglas@hotmail.com",
                            Password = "4DzGOIvFWK",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(2363),
                            Username = "Everette_Kutch21"
                        },
                        new
                        {
                            UserId = new Guid("30c8d9f4-5c19-48bc-9c8c-88f7d8a5e1af"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nedra_McGlynn@yahoo.com",
                            Password = "GU1zJ72vjx",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(2726),
                            Username = "Candelario.Brakus"
                        },
                        new
                        {
                            UserId = new Guid("5f20aec6-4013-4978-8f95-808cab3b2707"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Liana23@gmail.com",
                            Password = "dnSsZKawPp",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(3126),
                            Username = "Lina.Roob"
                        },
                        new
                        {
                            UserId = new Guid("1475fc1b-04f5-4017-a831-5fbe5b22aa21"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Onie.Koss@hotmail.com",
                            Password = "BUnP1Nusw4",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(3361),
                            Username = "Raul49"
                        },
                        new
                        {
                            UserId = new Guid("fe1702a9-c5d9-469f-b33d-5e0e6ecd141e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Raoul_Oberbrunner@hotmail.com",
                            Password = "1GdxwRtZCY",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(3690),
                            Username = "Constance60"
                        },
                        new
                        {
                            UserId = new Guid("9b8b85ac-46c3-4c3b-8b9c-c8e54de40f51"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Luis.Keebler@yahoo.com",
                            Password = "XIBn42igPv",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(3922),
                            Username = "Lawrence.Olson"
                        },
                        new
                        {
                            UserId = new Guid("9c1ab1b1-abde-4239-a4ec-b0f606d4cdbd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kayla55@hotmail.com",
                            Password = "bSbNKwSv1U",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(4231),
                            Username = "Erna79"
                        },
                        new
                        {
                            UserId = new Guid("19620c07-486e-47e6-b5d6-c17507f07cb4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Zelma86@yahoo.com",
                            Password = "5VithF2fcp",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(4469),
                            Username = "Robin.Beatty"
                        },
                        new
                        {
                            UserId = new Guid("2efcdc6d-fb44-4090-b935-92b2df74ed34"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Janis15@yahoo.com",
                            Password = "LW_wCceY7O",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(4980),
                            Username = "Bridgette.Strosin"
                        },
                        new
                        {
                            UserId = new Guid("502e184b-f407-4684-b51c-8bea1b4c8db0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rod.Veum@gmail.com",
                            Password = "Tl23wepE73",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(5223),
                            Username = "Colton8"
                        },
                        new
                        {
                            UserId = new Guid("a30e57c6-7bb6-432d-80b0-0229c6d3d685"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alphonso_Becker@yahoo.com",
                            Password = "QhDZSzUpMa",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(5614),
                            Username = "Emelie.Lubowitz88"
                        },
                        new
                        {
                            UserId = new Guid("4dbcedd8-d53c-45ff-976e-b504e1ce88ed"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Reva40@gmail.com",
                            Password = "KRf7U49BgR",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(5857),
                            Username = "Jana86"
                        },
                        new
                        {
                            UserId = new Guid("a302ef9e-2306-46cd-977b-987e15846a4f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Winona_Hauck@gmail.com",
                            Password = "tYmEhY43Em",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(6230),
                            Username = "Elise.Lockman47"
                        },
                        new
                        {
                            UserId = new Guid("0c2c768d-ee78-4fc6-819e-dd3134de72c5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Austen.Kerluke62@hotmail.com",
                            Password = "N3AkyaxhBJ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(6640),
                            Username = "Guy.OConner"
                        },
                        new
                        {
                            UserId = new Guid("e280f5d0-b000-4dd1-b886-642c267861ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Viviane_Hettinger@hotmail.com",
                            Password = "LuGyBoSDLt",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(7008),
                            Username = "Josiane_Collier"
                        },
                        new
                        {
                            UserId = new Guid("7b01c795-f227-4ddb-b684-b5bbbbe4fc35"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marilyne_Jacobi2@yahoo.com",
                            Password = "53rRHq29xI",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(7374),
                            Username = "Abigail_Jakubowski56"
                        },
                        new
                        {
                            UserId = new Guid("d7ec4e80-2681-40f2-be04-353cb635ae06"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Winifred84@gmail.com",
                            Password = "bgXbUfxVl9",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(7741),
                            Username = "Haley_Ankunding37"
                        },
                        new
                        {
                            UserId = new Guid("7999060d-1759-416f-921a-5676b813ed71"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alysa_Gibson8@gmail.com",
                            Password = "1Drm1vbPff",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(8013),
                            Username = "Brandi_OKeefe"
                        },
                        new
                        {
                            UserId = new Guid("acfd98f5-dd9b-4b66-8fe2-8976cf97d703"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Beatrice40@gmail.com",
                            Password = "0bj1EYU1tk",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(8380),
                            Username = "Serena.Larson"
                        },
                        new
                        {
                            UserId = new Guid("29fe2d5d-478c-412a-a40e-5b2f0278d350"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Melyssa_Jakubowski45@gmail.com",
                            Password = "S5GxnkEus3",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(8614),
                            Username = "Gina22"
                        },
                        new
                        {
                            UserId = new Guid("bc4f1c58-47a1-4dd7-b2fb-f81039ec161f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Neha_Abernathy@hotmail.com",
                            Password = "1NXIl19TjP",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(8981),
                            Username = "Aimee_Fadel"
                        },
                        new
                        {
                            UserId = new Guid("d42f5d03-8a0a-449e-9cc1-87fd76055e2f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Callie.Hartmann@gmail.com",
                            Password = "2ocHD3csHh",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(9220),
                            Username = "Frederik65"
                        },
                        new
                        {
                            UserId = new Guid("8037190c-9bba-49ef-838c-666efb337a75"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ashleigh32@yahoo.com",
                            Password = "QIPZvRxsDl",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(9523),
                            Username = "Arno77"
                        },
                        new
                        {
                            UserId = new Guid("23f96ad8-d381-47f1-bf7d-b15d58bd7a51"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Karina_Pouros@gmail.com",
                            Password = "eJIGatKfCp",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 633, DateTimeKind.Utc).AddTicks(9789),
                            Username = "Blaze.Ledner"
                        },
                        new
                        {
                            UserId = new Guid("1f3c8b4f-3cfa-455c-8aa0-95a29421ce7a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Zander15@gmail.com",
                            Password = "1J1LTtskgK",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(21),
                            Username = "Elena41"
                        },
                        new
                        {
                            UserId = new Guid("87ae7314-cf4d-4fe0-8025-89e9c3fedf1b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eliane_Schiller63@hotmail.com",
                            Password = "km4yjntQOT",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(456),
                            Username = "Myrtis.Cronin34"
                        },
                        new
                        {
                            UserId = new Guid("237446d4-1872-4da6-9658-88edf486b46b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kennedi.Durgan@hotmail.com",
                            Password = "CMemh6jm9H",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(680),
                            Username = "Junius.DuBuque"
                        },
                        new
                        {
                            UserId = new Guid("e1e62811-af4b-4ffd-8dc2-0a8625e635b1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dolores66@gmail.com",
                            Password = "FjN4Sd6m4t",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(966),
                            Username = "Freddie.Brakus"
                        },
                        new
                        {
                            UserId = new Guid("923a9e26-bc8c-4e1b-bd0f-3afb4619d18d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lori_Pouros@yahoo.com",
                            Password = "3ZbyFFMVgZ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(1195),
                            Username = "Katherine.Koch"
                        },
                        new
                        {
                            UserId = new Guid("be40ee8b-8a42-4acd-9dfa-cd0852d4eadc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Myrtie_Kshlerin@yahoo.com",
                            Password = "_f0b46m_KQ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(1509),
                            Username = "Herta_Gaylord"
                        },
                        new
                        {
                            UserId = new Guid("e5aab1ab-1932-40fe-82d4-404f87056eba"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Frederique.Carter15@hotmail.com",
                            Password = "RmcGpNUrz1",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(1772),
                            Username = "Jocelyn30"
                        },
                        new
                        {
                            UserId = new Guid("b2f63347-9d63-4148-aee0-11190be64d14"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Laurel_Bahringer@gmail.com",
                            Password = "VC3ZP873B_",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(2113),
                            Username = "Keira_Hahn"
                        },
                        new
                        {
                            UserId = new Guid("def161b2-48bb-4bcd-9dbd-a3415b111bf5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bradford82@yahoo.com",
                            Password = "0KsAkz4mB8",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(2341),
                            Username = "Rasheed.Koss"
                        },
                        new
                        {
                            UserId = new Guid("b9144eb1-4c48-4aaf-ab7c-1953647868de"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Greg.Weissnat@yahoo.com",
                            Password = "B4wz7yXCXf",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(2661),
                            Username = "Lonnie43"
                        },
                        new
                        {
                            UserId = new Guid("788cfca0-500c-4503-b083-41dd9e94ade1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Coleman_Murazik@gmail.com",
                            Password = "GFgOJP28Au",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(2913),
                            Username = "Ottis_Hyatt35"
                        },
                        new
                        {
                            UserId = new Guid("75f0e4e1-8765-49ac-ba46-5491a6e8377d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Isadore.Baumbach31@yahoo.com",
                            Password = "0HOUe1m0BH",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(3281),
                            Username = "Patrick66"
                        },
                        new
                        {
                            UserId = new Guid("b424d9ce-ba57-4d07-a3e5-542c68dd85ef"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dedric.Deckow@hotmail.com",
                            Password = "avPJ9XRCT_",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(3538),
                            Username = "Helene85"
                        },
                        new
                        {
                            UserId = new Guid("8d6d3375-491a-4ea3-bbc9-5ccb15af390b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Celestine.Gleichner@gmail.com",
                            Password = "yJQOwAUvD_",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(3906),
                            Username = "Abby.Cormier6"
                        },
                        new
                        {
                            UserId = new Guid("a0d9023a-7654-42a2-b312-d40863b8bf6f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Shana87@yahoo.com",
                            Password = "0m2ZkfSCae",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(4157),
                            Username = "Kyla.Pouros"
                        },
                        new
                        {
                            UserId = new Guid("a9e32d6b-250b-4357-afea-c578f0d134e9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rhea4@gmail.com",
                            Password = "bMvX24lknf",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(4439),
                            Username = "Arely_Rowe"
                        },
                        new
                        {
                            UserId = new Guid("3d95cca7-9b31-40a6-a17d-7ba19180ece5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tierra44@gmail.com",
                            Password = "Spm22galYp",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(4706),
                            Username = "Arthur24"
                        },
                        new
                        {
                            UserId = new Guid("0d9c3dbc-3c47-4038-b73a-7bc727a09f6d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alek.Kreiger42@yahoo.com",
                            Password = "8Qbq8TRaIq",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(5129),
                            Username = "Marina_Ruecker"
                        },
                        new
                        {
                            UserId = new Guid("1b839987-e1a4-49a3-8c4b-36c7c755b059"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Estrella.Beatty@hotmail.com",
                            Password = "Xg4TAHacvT",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(5382),
                            Username = "Audie_Carroll"
                        },
                        new
                        {
                            UserId = new Guid("8476fcd6-ac3c-42e5-bf13-9c3f60059053"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Emile_Rosenbaum@hotmail.com",
                            Password = "f7FeWvpQw9",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(5706),
                            Username = "Isabell35"
                        },
                        new
                        {
                            UserId = new Guid("fc7c2096-6971-4458-bbb3-046db64fa738"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Darron4@hotmail.com",
                            Password = "QngI1tq5NJ",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(5940),
                            Username = "Queenie24"
                        },
                        new
                        {
                            UserId = new Guid("e0c31c40-63f9-4043-a3d8-4e35dae24bd3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anderson_Metz@yahoo.com",
                            Password = "PcRlNn8aeE",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(6307),
                            Username = "Jaiden_Moen"
                        },
                        new
                        {
                            UserId = new Guid("bef17b6f-2c3a-4373-a65a-67971da05869"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Immanuel54@hotmail.com",
                            Password = "dgNNDkA5Pk",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(6537),
                            Username = "Nelle.Feeney"
                        },
                        new
                        {
                            UserId = new Guid("5c4db947-9b8e-4a0c-89f8-69828612106a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Shanny75@yahoo.com",
                            Password = "za0k8b5Tvn",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(6847),
                            Username = "Antonette_Senger"
                        },
                        new
                        {
                            UserId = new Guid("2a4e1a72-9d2e-4690-86ce-6b221959ba53"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jayson_OKeefe@gmail.com",
                            Password = "KvRUDPRhxu",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(7138),
                            Username = "Ashley_DAmore89"
                        },
                        new
                        {
                            UserId = new Guid("59861d43-b9b5-424e-a296-6fae7a9df105"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Braulio_Kuhic64@yahoo.com",
                            Password = "Q7zVoF6iKb",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(7465),
                            Username = "Maverick88"
                        },
                        new
                        {
                            UserId = new Guid("6394538b-583c-410a-adca-ef2734333a33"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Thurman0@hotmail.com",
                            Password = "b9JkvZgqjs",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(7714),
                            Username = "Aidan.Davis69"
                        },
                        new
                        {
                            UserId = new Guid("9268ec87-7f52-4a7a-9c75-60fb9fd7d90a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kennedi.Erdman@yahoo.com",
                            Password = "wpuyRj8qY8",
                            UpdatedAt = new DateTime(2022, 11, 4, 9, 1, 25, 634, DateTimeKind.Utc).AddTicks(8087),
                            Username = "Shirley63"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
