// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ipt_project_cepbep.Data;

#nullable disable

namespace iptprojectcepbep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ipt_project_cepbep.Models.Canvas_Model", b =>
            {
                b.Property<string>("Canvas_id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text");

                b.Property<string>("Colors")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("User_id")
                    .HasColumnType("uuid");

                b.HasKey("Canvas_id");

                b.HasIndex("User_id");

                b.ToTable("canvas");
                modelBuilder.Entity("ipt_project_cepbep.Models.Friend", b =>
                {
                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("friend");
                });

                modelBuilder.Entity("ipt_project_cepbep.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user");
                });

                modelBuilder.Entity("ipt_project_cepbep.Models.Canvas_Model", b =>
                {
                    b.HasOne("ipt_project_cepbep.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                    b.HasData(
                        new
                        {
                            UserId = new Guid("22133462-db54-4cb5-ac09-866ad5c8558b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Elizabeth.Bailey96@yahoo.com",
                            Password = "lFE6N55uYI",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 915, DateTimeKind.Utc).AddTicks(9732),
                            Username = "Arnold83"
                        },
                        new
                        {
                            UserId = new Guid("73af5318-6ef9-41b5-bf0d-d07387df9715"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Darryl55@gmail.com",
                            Password = "6E017C6tnb",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 915, DateTimeKind.Utc).AddTicks(9936),
                            Username = "Tatum_Boyle"
                        },
                        new
                        {
                            UserId = new Guid("cdaddb4a-ec5d-4d25-8ecb-33558668ec91"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maida_Block@yahoo.com",
                            Password = "nCVCShw5ns",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(108),
                            Username = "Odell.Leannon"
                        },
                        new
                        {
                            UserId = new Guid("d2ab8713-f34a-4f49-9b4b-abd3b121fd1f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brendan95@yahoo.com",
                            Password = "0vRXaVSz_g",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(246),
                            Username = "Shania85"
                        },
                        new
                        {
                            UserId = new Guid("6a9802a8-604b-4c3e-b342-854304a75c01"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jabari_Boyer81@gmail.com",
                            Password = "dL49zpOEzb",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(442),
                            Username = "Lincoln69"
                        },
                        new
                        {
                            UserId = new Guid("1d578ac1-9e30-41cc-b3f8-dfacb6abb279"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Destin.Lowe@yahoo.com",
                            Password = "1W1s8DFMYt",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(590),
                            Username = "Orrin12"
                        },
                        new
                        {
                            UserId = new Guid("f926de78-afcd-4bde-8d5d-84453c84e86f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Burley.Ortiz86@gmail.com",
                            Password = "P9GR1jNE4_",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(760),
                            Username = "Vicente_Barrows"
                        },
                        new
                        {
                            UserId = new Guid("ee1330b2-906a-4fc8-9110-0651ec5591e6"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cynthia.Tromp@gmail.com",
                            Password = "rn4iu8a5XS",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(904),
                            Username = "Camilla_Olson95"
                        },
                        new
                        {
                            UserId = new Guid("b00e09ab-3802-461e-8de0-f61315698857"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Margaret_Hauck18@hotmail.com",
                            Password = "gPPILaVfD1",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1061),
                            Username = "Ivah.Cummerata"
                        },
                        new
                        {
                            UserId = new Guid("d77a7959-40e9-4bda-8a6f-89e0c2439aaf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dale_Thiel94@gmail.com",
                            Password = "LoisWnY6eU",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1185),
                            Username = "Sylvan.Frami"
                        },
                        new
                        {
                            UserId = new Guid("ed626b5d-c2dc-4de3-af9c-e7004a79d841"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kenna_Dicki0@gmail.com",
                            Password = "dwABsWZbkH",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1344),
                            Username = "Keely57"
                        },
                        new
                        {
                            UserId = new Guid("222b535b-e81a-4a38-84e1-a5f6def2e9b1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Harmon44@yahoo.com",
                            Password = "RK3cTn_GDc",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1486),
                            Username = "Franco81"
                        },
                        new
                        {
                            UserId = new Guid("c609d793-8737-4c3e-9038-4d7e4b5f4d1c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jaylon0@hotmail.com",
                            Password = "ht5CJbY37L",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1681),
                            Username = "Lloyd.Schuppe"
                        },
                        new
                        {
                            UserId = new Guid("1da6977f-c8d9-4828-8767-fb2f1a823637"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Vince_Botsford@yahoo.com",
                            Password = "mH0ZrqAkAG",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1814),
                            Username = "Kaleb61"
                        },
                        new
                        {
                            UserId = new Guid("3d053b0b-3663-4314-bf57-e7fcfd3ca472"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eloisa.Murazik@hotmail.com",
                            Password = "znMH3mGPIE",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(1952),
                            Username = "Jaquelin.Jast"
                        },
                        new
                        {
                            UserId = new Guid("4150ddd9-8140-4e7a-b8c0-ef9e23642b30"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Virgie13@hotmail.com",
                            Password = "CJO0sX5BV8",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2111),
                            Username = "Onie_Hickle"
                        },
                        new
                        {
                            UserId = new Guid("ade9e8d5-9783-4e29-a893-4dbacc34defe"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jennings_Koss@hotmail.com",
                            Password = "2fDWxvNO2C",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2251),
                            Username = "Ryder_Mueller1"
                        },
                        new
                        {
                            UserId = new Guid("a5b1530a-c85d-4d55-a377-bb5a9f0d242d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Karolann.Stark1@yahoo.com",
                            Password = "qKkAU2TH4f",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2478),
                            Username = "Aimee_Kohler77"
                        },
                        new
                        {
                            UserId = new Guid("8ae8b69d-40bb-41e7-97a7-3020f8b49783"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Arvel.Hartmann@yahoo.com",
                            Password = "9diHg3w8i7",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2608),
                            Username = "Rex82"
                        },
                        new
                        {
                            UserId = new Guid("71ba835a-a6c6-4380-ba20-cefc874abd75"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jewel.Reinger3@gmail.com",
                            Password = "Pyc26bCNZX",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2793),
                            Username = "Donavon_Nicolas37"
                        },
                        new
                        {
                            UserId = new Guid("8659bed5-6f44-4c37-81cd-47c491e41bc4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lori_Murray36@gmail.com",
                            Password = "6Q9qFn6J8t",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(2946),
                            Username = "Lura15"
                        },
                        new
                        {
                            UserId = new Guid("42adb523-a241-4b0c-8850-485c004aa97e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tyrique76@hotmail.com",
                            Password = "ivccelW9_V",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(3098),
                            Username = "Solon.Ward"
                        },
                        new
                        {
                            UserId = new Guid("dbbe53ed-4941-45a1-88a2-517834b03a8e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Estrella.Tillman@yahoo.com",
                            Password = "DXMKgXg15l",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(3233),
                            Username = "Oral96"
                        },
                        new
                        {
                            UserId = new Guid("2782efb8-3aa6-437d-8aae-b46732db9e23"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexane.Skiles64@hotmail.com",
                            Password = "g6yWqKXiUq",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(3408),
                            Username = "Alize.Trantow4"
                        },
                        new
                        {
                            UserId = new Guid("d3c6be15-1d26-46d2-af23-71803104b4ad"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Diego50@hotmail.com",
                            Password = "vhJw7AmCVX",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(3548),
                            Username = "Brandt51"
                        },
                        new
                        {
                            UserId = new Guid("fd64c5c6-3e44-4435-9887-ec7f38c8b282"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alba91@hotmail.com",
                            Password = "krzBa2c5S1",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(3714),
                            Username = "Aidan_Kuhic"
                        },
                        new
                        {
                            UserId = new Guid("91de3057-0ab9-468d-92dd-09b070ae7c0f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nettie_Rodriguez@gmail.com",
                            Password = "pR2S7BxCTi",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(4519),
                            Username = "Bailey.OReilly"
                        },
                        new
                        {
                            UserId = new Guid("a512feb8-1a16-4f39-ac24-cd7c50530ac1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lucy.Huel@gmail.com",
                            Password = "RffU1Jz3Ty",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(4697),
                            Username = "Lilyan.Hermann"
                        },
                        new
                        {
                            UserId = new Guid("a510bfac-004d-4d4e-8182-2e3d52aaf994"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Emory65@hotmail.com",
                            Password = "jgFN56g_BG",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(4827),
                            Username = "Lavern.Kub59"
                        },
                        new
                        {
                            UserId = new Guid("4b9a6a5d-acdf-49c6-9a74-d2db3e020151"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eulalia_Corkery@gmail.com",
                            Password = "V7wUVNniRV",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(4955),
                            Username = "Keara.Ryan12"
                        },
                        new
                        {
                            UserId = new Guid("821bb529-c2e1-423e-ba61-8a98d6cdbc1b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexanne.Thompson4@hotmail.com",
                            Password = "mNpPqHKZFu",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5123),
                            Username = "Russell65"
                        },
                        new
                        {
                            UserId = new Guid("2dbbd163-7842-4c1a-a6d9-efe758f665b7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jaren.Tremblay@hotmail.com",
                            Password = "DBVQQSARmR",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5274),
                            Username = "Verona37"
                        },
                        new
                        {
                            UserId = new Guid("68fe3a70-846b-4f6d-ad4c-e62127d66036"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kyleigh30@yahoo.com",
                            Password = "9QTA2kf_jB",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5428),
                            Username = "Maryse47"
                        },
                        new
                        {
                            UserId = new Guid("55619707-5eaf-4bf6-a14f-14837ea0982e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Barry42@yahoo.com",
                            Password = "SecyphLptJ",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5641),
                            Username = "Walker50"
                        },
                        new
                        {
                            UserId = new Guid("fae1ea8f-fc07-4b99-8436-69dfcbf432ca"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Granville7@hotmail.com",
                            Password = "XtbiTjKhPT",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5776),
                            Username = "Greyson.Lang"
                        },
                        new
                        {
                            UserId = new Guid("fe9b1208-a636-461b-b9d9-bab6ba5a7311"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maximo.Schuppe@yahoo.com",
                            Password = "NS00J_xhEm",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(5904),
                            Username = "Yolanda85"
                        },
                        new
                        {
                            UserId = new Guid("5c538e8c-28ad-4fce-bfc9-3f950c260592"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Daryl_Daugherty@hotmail.com",
                            Password = "C_UB3ymtWV",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6072),
                            Username = "Kim_Hodkiewicz"
                        },
                        new
                        {
                            UserId = new Guid("29acb5cc-51f6-4917-80db-10d727b9ea25"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kailyn_Robel85@gmail.com",
                            Password = "kbqfOew2Sh",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6237),
                            Username = "Valerie_Vandervort32"
                        },
                        new
                        {
                            UserId = new Guid("d8b927fe-00f9-435c-8f3e-f562a49dd72f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Parker.Abbott@gmail.com",
                            Password = "q0pC5trNoj",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6377),
                            Username = "Verna_Hamill21"
                        },
                        new
                        {
                            UserId = new Guid("272f2c71-e859-4804-96da-f44e56abb8de"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lucio_Jacobi27@yahoo.com",
                            Password = "hGz1981sES",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6519),
                            Username = "Cole_Marquardt"
                        },
                        new
                        {
                            UserId = new Guid("87c7f901-ac55-4ea1-8a70-8177391c2e7c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lourdes74@hotmail.com",
                            Password = "abzQrBGLGv",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6663),
                            Username = "Gabriel.Marks"
                        },
                        new
                        {
                            UserId = new Guid("1ba310df-2553-4406-a270-9417068e049a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tania.Schinner83@yahoo.com",
                            Password = "evH6LSjQdz",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6800),
                            Username = "Lauren.Schulist"
                        },
                        new
                        {
                            UserId = new Guid("565b1726-0a05-486b-bdcf-37b367a45d87"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Duane_Effertz30@gmail.com",
                            Password = "n4yuiM2QYw",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(6973),
                            Username = "America_Collier42"
                        },
                        new
                        {
                            UserId = new Guid("e31549e6-9c2e-4e46-915f-c9d5e2a99e0e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Florence52@gmail.com",
                            Password = "breRtbGddV",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7125),
                            Username = "Braxton.Gaylord"
                        },
                        new
                        {
                            UserId = new Guid("92197a3e-cdce-470f-b28d-4dd20b9a1e24"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Danielle.Heathcote64@yahoo.com",
                            Password = "Md5avQlcM8",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7270),
                            Username = "Carter54"
                        },
                        new
                        {
                            UserId = new Guid("0b53ea6a-343e-4de9-9503-61b9d846a5b8"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marietta_Zemlak1@hotmail.com",
                            Password = "2z2heLNdcm",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7444),
                            Username = "Tomas_Langosh75"
                        },
                        new
                        {
                            UserId = new Guid("14d477fb-6a80-4c1a-8016-62bb928fb1d4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Porter.Jerde82@gmail.com",
                            Password = "nimlgc4jpA",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7576),
                            Username = "Ellen_Miller"
                        },
                        new
                        {
                            UserId = new Guid("5386f960-de96-41ac-95ce-ae437503c378"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marge99@yahoo.com",
                            Password = "ni8NkwRwQi",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7730),
                            Username = "Bradly_Larkin"
                        },
                        new
                        {
                            UserId = new Guid("4b9417f4-8543-4237-872d-96c2dd802782"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sophie_Anderson68@yahoo.com",
                            Password = "G8tMHatuKS",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(7877),
                            Username = "Marielle_Wilkinson"
                        },
                        new
                        {
                            UserId = new Guid("182bcb8b-c6f6-49c6-891d-9d5342f2126e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Vito79@yahoo.com",
                            Password = "MYexEsM_H7",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8035),
                            Username = "Beatrice40"
                        },
                        new
                        {
                            UserId = new Guid("a73dff94-8f4b-475b-8715-d2451f50bd72"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Warren.Hoppe44@gmail.com",
                            Password = "gT2YlboJOt",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8172),
                            Username = "Gunnar.Little"
                        },
                        new
                        {
                            UserId = new Guid("24d15854-5a04-483b-b6f8-91c66309c19b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Keely_Adams@yahoo.com",
                            Password = "4_XPw8KDYB",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8288),
                            Username = "Thad21"
                        },
                        new
                        {
                            UserId = new Guid("2a48f2d4-a4d2-41c1-b403-dd59880e0001"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Olin41@gmail.com",
                            Password = "mNeyy9D70B",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8435),
                            Username = "Kelli80"
                        },
                        new
                        {
                            UserId = new Guid("0f7a8f91-16a0-444b-a923-ad37a9ece2b0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Clement16@hotmail.com",
                            Password = "qtrXElTyCv",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8573),
                            Username = "Josefina28"
                        },
                        new
                        {
                            UserId = new Guid("cff6251a-77c8-4015-821c-446b4b220dba"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jailyn96@hotmail.com",
                            Password = "UQTLsDwbSu",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8725),
                            Username = "Thad_Collins"
                        },
                        new
                        {
                            UserId = new Guid("48e39d82-2f79-4db2-b217-141681457520"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Federico_Morissette@hotmail.com",
                            Password = "vFm2aspqho",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(8863),
                            Username = "Ryder93"
                        },
                        new
                        {
                            UserId = new Guid("174463d1-bf48-47c6-b3dc-7104cad680bd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Amya.Cummerata78@yahoo.com",
                            Password = "HiyL9cwtPo",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9017),
                            Username = "Harmon.Abbott"
                        },
                        new
                        {
                            UserId = new Guid("465f0c6f-d279-4209-bc20-627b80d6842b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jamison_Reynolds8@hotmail.com",
                            Password = "w8vM3hj4_c",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9155),
                            Username = "Sylvia_Langosh"
                        },
                        new
                        {
                            UserId = new Guid("47658408-4bae-4266-b23b-453847bb04a1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosendo36@yahoo.com",
                            Password = "MF2NGUDmZu",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9308),
                            Username = "Maxie18"
                        },
                        new
                        {
                            UserId = new Guid("c6a77a45-c00f-4cfb-b040-a1a157639b38"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lionel.Hodkiewicz@hotmail.com",
                            Password = "iJjSQprmiP",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9445),
                            Username = "Albina_Hagenes"
                        },
                        new
                        {
                            UserId = new Guid("debf1ece-0842-46f7-9c23-46aece3225a0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rhiannon.Waelchi45@hotmail.com",
                            Password = "gUaIRJ7UlX",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9604),
                            Username = "Monroe_Walsh"
                        },
                        new
                        {
                            UserId = new Guid("777bb37b-78a8-4a06-a330-1eeec2bf74ab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bettie_Bauch82@gmail.com",
                            Password = "zbl7qm0Xp8",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9745),
                            Username = "Alia_Parker"
                        },
                        new
                        {
                            UserId = new Guid("3616b50a-d4bd-4e61-8164-865e9e3c1871"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kristina_Gutmann5@yahoo.com",
                            Password = "hGtBxeBwfg",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 916, DateTimeKind.Utc).AddTicks(9908),
                            Username = "Roosevelt_Mayer43"
                        },
                        new
                        {
                            UserId = new Guid("d250c35d-9760-408e-8d8d-1c463ff9dc58"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Pablo.Fay54@yahoo.com",
                            Password = "OG9yWDJ34A",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(53),
                            Username = "Mandy71"
                        },
                        new
                        {
                            UserId = new Guid("68561321-71b7-4409-8596-6e501a1986ef"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Virgil77@hotmail.com",
                            Password = "KI2b5DLrAh",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(220),
                            Username = "Ferne.Kshlerin"
                        },
                        new
                        {
                            UserId = new Guid("9b258e08-5615-4da2-b979-3eb451529b5f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kaci_Schulist30@gmail.com",
                            Password = "dRUXeUTCBY",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(349),
                            Username = "Omari.Hudson"
                        },
                        new
                        {
                            UserId = new Guid("778193ac-0dd7-4aa1-935b-e8cc8b503db5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Colby.Kutch@yahoo.com",
                            Password = "NMNj8JVv8Q",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(520),
                            Username = "Katheryn_Reinger"
                        },
                        new
                        {
                            UserId = new Guid("954d355e-be33-43a8-a3c8-a53901224d33"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jessie0@yahoo.com",
                            Password = "ce051CwlVP",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(658),
                            Username = "Johnpaul11"
                        },
                        new
                        {
                            UserId = new Guid("a94cbcc0-a805-44e4-a15d-4f6d6828d2e4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Justus96@gmail.com",
                            Password = "nCZsURhsCr",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(806),
                            Username = "Yadira.Mills"
                        },
                        new
                        {
                            UserId = new Guid("994bb89b-244e-4051-ae64-97bedbae0975"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ryann.Smith@hotmail.com",
                            Password = "xe5kO3tQ5u",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(935),
                            Username = "Angie_Pagac"
                        },
                        new
                        {
                            UserId = new Guid("65434d8c-9b01-47e4-88bf-c320179c59e2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Meda_Pagac49@yahoo.com",
                            Password = "fv_IvapAi1",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1049),
                            Username = "Lew_Huel8"
                        },
                        new
                        {
                            UserId = new Guid("0a8fc1d5-446e-473a-9d9f-275939608fbf"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Erin_Tremblay36@hotmail.com",
                            Password = "0lDcvVwqEx",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1231),
                            Username = "Freida.Gleichner90"
                        },
                        new
                        {
                            UserId = new Guid("0f7b091f-0838-4aa9-8e67-cc56ecff358e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bartholome1@yahoo.com",
                            Password = "5LpExZ70yV",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1364),
                            Username = "Hazel68"
                        },
                        new
                        {
                            UserId = new Guid("7990a3fa-2ac1-4626-a4a2-b965d6fb9584"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kamron.Kohler23@yahoo.com",
                            Password = "D7pxKJ0ib5",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1517),
                            Username = "Jaunita.Rutherford76"
                        },
                        new
                        {
                            UserId = new Guid("34f36fa0-dde4-4b76-b168-a8561330dab9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kris.Predovic20@gmail.com",
                            Password = "_7cYarrzBB",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1678),
                            Username = "Green_Gerhold"
                        },
                        new
                        {
                            UserId = new Guid("e2f706ea-304b-4374-8fec-056feb366c2b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Abagail_Ferry73@yahoo.com",
                            Password = "ABc9Rd1j2K",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1809),
                            Username = "Eloy55"
                        },
                        new
                        {
                            UserId = new Guid("748f66eb-dcbd-48d0-a61d-898e23fb7728"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Queenie.Mann39@gmail.com",
                            Password = "nZVDOqRlZ9",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(1945),
                            Username = "Milton_Muller81"
                        },
                        new
                        {
                            UserId = new Guid("6159cb17-349a-47a1-a3dc-501313acf0d7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bud.Robel11@hotmail.com",
                            Password = "_oxuTTQqCw",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(2099),
                            Username = "Humberto_Batz"
                        },
                        new
                        {
                            UserId = new Guid("7b0164b5-a22d-42b4-ae8d-c710daa46010"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trevor34@hotmail.com",
                            Password = "BFD5OSNAmB",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(2241),
                            Username = "Catalina.Corwin99"
                        },
                        new
                        {
                            UserId = new Guid("69f90e8a-9b6b-4028-902f-ff9217f6fc09"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Robin_DAmore53@hotmail.com",
                            Password = "TmUFfQZX28",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(2460),
                            Username = "Wilford.Herman75"
                        },
                        new
                        {
                            UserId = new Guid("e5ac3a67-6333-4bf7-8602-b998e2b63356"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Skyla33@gmail.com",
                            Password = "UFlZvjq0ia",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(2629),
                            Username = "Bryce.Pollich29"
                        },
                        new
                        {
                            UserId = new Guid("9693dc45-9ee4-433c-bb5d-9205e90e6099"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rowland.Wilderman@gmail.com",
                            Password = "4MIQet_kYp",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(2844),
                            Username = "Cathrine_Jones"
                        },
                        new
                        {
                            UserId = new Guid("091e5e9e-5f92-482f-b808-d65eed7bb8ed"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "May.Stoltenberg45@gmail.com",
                            Password = "CuccTGyL8W",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3053),
                            Username = "Sebastian_Sporer48"
                        },
                        new
                        {
                            UserId = new Guid("7c4eec42-a9c7-4c04-af73-66c0ac97ceb1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wiley.Lynch10@yahoo.com",
                            Password = "pavIkbmJ5C",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3187),
                            Username = "Sofia_Streich83"
                        },
                        new
                        {
                            UserId = new Guid("22b7465a-4730-4270-8115-8eaf53edc910"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ladarius_Paucek@gmail.com",
                            Password = "m5Y7YKDCfj",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3387),
                            Username = "Samson.Macejkovic33"
                        },
                        new
                        {
                            UserId = new Guid("03e065f9-1e3b-405b-a9e5-2dd3d50ac373"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nikki.Breitenberg@gmail.com",
                            Password = "klcDCU7nxZ",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3564),
                            Username = "Thora44"
                        },
                        new
                        {
                            UserId = new Guid("81344f17-cc77-4b87-9ed9-400290a46025"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Janick84@gmail.com",
                            Password = "rZMn0hD6L4",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3707),
                            Username = "Adeline.Fadel57"
                        },
                        new
                        {
                            UserId = new Guid("3ae0680e-2b0f-4dbf-a7db-1177570a44e4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Freda.Spencer@gmail.com",
                            Password = "KmBaAuVpJo",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(3878),
                            Username = "Rebecca_Larkin89"
                        },
                        new
                        {
                            UserId = new Guid("c8d288ff-0e2a-42c6-ae5b-af8300cb18dc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Abner.Batz@hotmail.com",
                            Password = "cwqhu1tBee",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4017),
                            Username = "Mia63"
                        },
                        new
                        {
                            UserId = new Guid("3fb94ecc-b2e0-4a3e-a5e3-3b61c5ee3bc0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mavis.Bechtelar@hotmail.com",
                            Password = "qMOBSJVZ_s",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4173),
                            Username = "Ken_Denesik86"
                        },
                        new
                        {
                            UserId = new Guid("5ad38550-dc72-43b6-9cd2-9e7b99676bab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cynthia_Littel@hotmail.com",
                            Password = "uhuYfVnSrS",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4308),
                            Username = "Josefa10"
                        },
                        new
                        {
                            UserId = new Guid("a67dfb22-e579-43b1-a110-bfcb44b0b53b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosemarie_Connelly27@hotmail.com",
                            Password = "sMHnGKMk_n",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4488),
                            Username = "Jasmin.Moen"
                        },
                        new
                        {
                            UserId = new Guid("69661be0-3d64-4e30-b7f7-66063f699f04"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eldridge_Kiehn@gmail.com",
                            Password = "zvGmgvUz1q",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4622),
                            Username = "Ernest80"
                        },
                        new
                        {
                            UserId = new Guid("4c4f9b08-2a35-4fd1-8931-c546c73b2fe3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Isidro46@yahoo.com",
                            Password = "by8Wjja1ne",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4794),
                            Username = "Brionna87"
                        },
                        new
                        {
                            UserId = new Guid("193747a6-72e7-49f4-8e4e-64d56a468a9c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Heidi_Schuppe@hotmail.com",
                            Password = "k3JIYGoGsz",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(4978),
                            Username = "Ellie.OKeefe29"
                        },
                        new
                        {
                            UserId = new Guid("cc8c2dcd-1e38-4b67-9132-1671ee7ee4ce"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Yasmin.Dietrich@yahoo.com",
                            Password = "R9tCOwiNQn",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(5134),
                            Username = "Graham1"
                        },
                        new
                        {
                            UserId = new Guid("adda5d30-242a-49c9-9656-6f2eb859fabc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Genevieve23@gmail.com",
                            Password = "NK4ShwGIOc",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(5266),
                            Username = "Scottie_Hauck"
                        },
                        new
                        {
                            UserId = new Guid("bac49b08-6b5c-452d-b0cb-eb65a09cbea8"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jaqueline40@yahoo.com",
                            Password = "nxcsGKt73Y",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(5415),
                            Username = "Billy_Lehner36"
                        },
                        new
                        {
                            UserId = new Guid("f8eaf74d-b312-4169-939d-22fb1778af5a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Grant.Terry84@gmail.com",
                            Password = "J3_ZXvNmWR",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(5557),
                            Username = "Elnora_Stiedemann62"
                        },
                        new
                        {
                            UserId = new Guid("a53c89cd-5bba-4f8a-8a4e-06f53f4eae23"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Connor.Schaden92@hotmail.com",
                            Password = "UpEPhZgx5z",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 5, 1, 46, 48, 917, DateTimeKind.Utc).AddTicks(5810),
                            Username = "Jeremy_Rodriguez18"
                        });
                });

                modelBuilder.Entity("ipt_project_cepbep.Models.Friend", b =>
                {
                    b.HasOne("ipt_project_cepbep.Models.User", "ToFriend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ipt_project_cepbep.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToFriend");

                    b.Navigation("User");
                });
            });
        }
    }
}

