version: '1'

services:
  next-app:
    container_name: ipt-web
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ipt-net

networks:
  ipt-net:
    external: true
    